server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          # lb 代表 loadbalance ：负载均衡，因为使用了负载均衡，所以需要导入spring-cloud-loadbalancer依赖
          uri: lb://ConnectX-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://ConnectX-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://ConnectX-subject
          predicates:
            - Path=/subject/**
